### ISSUE TITLE
customize for quill

### ISSUE THREAD

**Issue by YoshiyukiSakura** [opensquare-network/previewer#38]
### add CSS
 ```css
 ol > li[data-list="bullet"] {
    display: list-item;
    ::before{
      content: "•";
      unicode-bidi: isolate;
      font-variant-numeric: tabular-nums;
      text-transform: none;
      text-indent: 0px !important;
      text-align: start !important;
      text-align-last: start !important;
    }
  }
```
